--[[
    @author: THEGizmo
    @copyright: 2022-2023
    @description: Models Dev for the Map Editor
    All rights reserved
]]--

loaderDev = {
    devs = {
        {id=1518, col="dev_tv_1", txd="dev_tv_all", dff="dev_tv_1", alpha=false, directory="models/dev/"},
        {id=1717, col="dev_tv_2", txd="dev_tv_all", dff="dev_tv_2", alpha=false, directory="models/dev/"},
        {id=1747, col="dev_tv_3", txd="dev_tv_all", dff="dev_tv_3", alpha=false, directory="models/dev/"},
        {id=1748, col="dev_tv_4", txd="dev_tv_all", dff="dev_tv_4", alpha=false, directory="models/dev/"},
        {id=1749, col="dev_tv_5", txd="dev_tv_all", dff="dev_tv_5", alpha=false, directory="models/dev/"},
        {id=1750, col="dev_tv_6", txd="dev_tv_all", dff="dev_tv_6", alpha=false, directory="models/dev/"},
        {id=1751, col="dev_tv_7", txd="dev_tv_all", dff="dev_tv_7", alpha=false, directory="models/dev/"},
        {id=1752, col="dev_tv_8", txd="dev_tv_all", dff="dev_tv_8", alpha=false, directory="models/dev/"},
        {id=1781, col="dev_tv_9", txd="dev_tv_all", dff="dev_tv_9", alpha=false, directory="models/dev/"},
        {id=1786, col="dev_tv_10", txd="dev_tv_all", dff="dev_tv_10", alpha=false, directory="models/dev/"},
        {id=2344, col="dev_tv_11", txd="dev_tv_all", dff="dev_tv_11", alpha=false, directory="models/dev/"},
        {id=1718, col="dev_console_1", txd="dev_console_all", dff="dev_console_1", alpha=false, directory="models/dev/"},
        {id=1719, col="dev_console_2", txd="dev_console_all", dff="dev_console_2", alpha=false, directory="models/dev/"},
        {id=1782, col="dev_console_3", txd="dev_console_all", dff="dev_console_3", alpha=false, directory="models/dev/"},
        {id=1783, col="dev_dvd_1", txd="dev_dvd_all", dff="dev_dvd_1", alpha=false, directory="models/dev/"},
        {id=1785, col="dev_dvd_2", txd="dev_dvd_all", dff="dev_dvd_2", alpha=false, directory="models/dev/"},
        {id=1787, col="dev_dvd_3", txd="dev_dvd_all", dff="dev_dvd_3", alpha=false, directory="models/dev/"},
        {id=1840, col="dev_speaker_1", txd="dev_speaker_all", dff="dev_speaker_1", alpha=false, directory="models/dev/"},
        {id=1841, col="dev_speaker_2", txd="dev_speaker_all", dff="dev_speaker_2", alpha=false, directory="models/dev/"},
        {id=2224, col="dev_speaker_3", txd="dev_speaker_all", dff="dev_speaker_3", alpha=false, directory="models/dev/"}, 
        {id=2836, col="dev_carpet_1", txd="dev_carpet_all", dff="dev_carpet_1", alpha=false, directory="models/dev/"},
        {id=2841, col="dev_carpet_2", txd="dev_carpet_all", dff="dev_carpet_2", alpha=false, directory="models/dev/"},
        {id=2842, col="dev_carpet_3", txd="dev_carpet_all", dff="dev_carpet_3", alpha=false, directory="models/dev/"},
        {id=2847, col="dev_carpet_4", txd="dev_carpet_all", dff="dev_carpet_4", alpha=false, directory="models/dev/"},
        {id=2190, col="dev_pc_1", txd="dev_pc_all", dff="dev_pc_1", alpha=false, directory="models/dev/"},
        {id=2201, col="dev_pc_2", txd="dev_pc_all", dff="dev_pc_2", alpha=false, directory="models/dev/"},
        {id=2202, col="dev_pc_3", txd="dev_pc_all", dff="dev_pc_3", alpha=false, directory="models/dev/"},
        {id=1791, col="dev_pc_4", txd="dev_pc_all", dff="dev_pc_4", alpha=false, directory="models/dev/"},
        {id=1792, col="dev_pc_5", txd="dev_pc_all", dff="dev_pc_5", alpha=false, directory="models/dev/"},
        {id=2097, col="dev_toilet_1", txd="dev_toilet_all", dff="dev_toilet_1", alpha=false, directory="models/dev/"},
        {id=2521, col="dev_toilet_2", txd="dev_toilet_all", dff="dev_toilet_2", alpha=false, directory="models/dev/"},
        {id=2523, col="dev_toilet_3", txd="dev_toilet_all", dff="dev_toilet_3", alpha=false, directory="models/dev/"},
        {id=2741, col="dev_toilet_4", txd="dev_toilet_all", dff="dev_toilet_4", alpha=false, directory="models/dev/"},
        {id=2742, col="dev_toilet_5", txd="dev_toilet_all", dff="dev_toilet_5", alpha=false, directory="models/dev/"},
        {id=14481, col="dev_toilet_6", txd="dev_toilet_all", dff="dev_toilet_6", alpha=false, directory="models/dev/"},
        {id=14494, col="dev_toilet_7", txd="dev_toilet_all", dff="dev_toilet_7", alpha=false, directory="models/dev/"},
        {id=1541, col="dev_machine_1", txd="dev_machine_all", dff="dev_machine_1", alpha=false, directory="models/dev/"},
        {id=1542, col="dev_machine_2", txd="dev_machine_all", dff="dev_machine_2", alpha=false, directory="models/dev/"},
        {id=2203, col="dev_flower_1", txd="dev_flower_all", dff="dev_flower_1", alpha=false, directory="models/dev/"},
        {id=2194, col="dev_flower_2", txd="dev_flower_all", dff="dev_flower_2", alpha=false, directory="models/dev/"},
        {id=2247, col="dev_flower_3", txd="dev_flower_all", dff="dev_flower_3", alpha=false, directory="models/dev/"},
        {id=2250, col="dev_flower_4", txd="dev_flower_all", dff="dev_flower_4", alpha=false, directory="models/dev/"},
        {id=2249, col="dev_flower_5", txd="dev_flower_all", dff="dev_flower_5", alpha=false, directory="models/dev/"},
        {id=1793, col="dev_sofa_1", txd="dev_sofa_all", dff="dev_sofa_1", alpha=false, directory="models/dev/"},
        {id=1728, col="dev_sofa_2", txd="dev_sofa_all", dff="dev_sofa_2", alpha=false, directory="models/dev/"},
        {id=1729, col="dev_sofa_3", txd="dev_sofa_all", dff="dev_sofa_3", alpha=false, directory="models/dev/"},
        {id=1735, col="dev_sofa_4", txd="dev_sofa_all", dff="dev_sofa_4", alpha=false, directory="models/dev/"},
        {id=1705, col="dev_sofa_5", txd="dev_sofa_all", dff="dev_sofa_5", alpha=false, directory="models/dev/"},
        {id=1708, col="dev_sofa_6", txd="dev_sofa_all", dff="dev_sofa_6", alpha=false, directory="models/dev/"},
        {id=1722, col="dev_chair_1", txd="dev_chair_all", dff="dev_chair_1", alpha=false, directory="models/dev/"},
        {id=1806, col="dev_chair_2", txd="dev_chair_all", dff="dev_chair_2", alpha=false, directory="models/dev/"},
        {id=2122, col="dev_chair_3", txd="dev_chair_all", dff="dev_chair_3", alpha=false, directory="models/dev/"},
        {id=2309, col="dev_chair_4", txd="dev_chair_all", dff="dev_chair_4", alpha=false, directory="models/dev/"},
        {id=2356, col="dev_chair_5", txd="dev_chair_all", dff="dev_chair_5", alpha=false, directory="models/dev/"},
        {id=1826, col="dev_table_1", txd="dev_table_all", dff="dev_table_1", alpha=false, directory="models/dev/"},
        {id=1827, col="dev_table_2", txd="dev_table_all", dff="dev_table_2", alpha=false, directory="models/dev/"},
        {id=2209, col="dev_table_3", txd="dev_table_all", dff="dev_table_3", alpha=false, directory="models/dev/"},
        {id=2370, col="dev_table_4", txd="dev_table_all", dff="dev_table_4", alpha=false, directory="models/dev/"}, 
        {id=2046, col="dev_cupboard_1", txd="dev_cupboard_all", dff="dev_cupboard_1", alpha=false, directory="models/dev/"},
        {id=2078, col="dev_cupboard_2", txd="dev_cupboard_all", dff="dev_cupboard_2", alpha=false, directory="models/dev/"},
        {id=2089, col="dev_cupboard_3", txd="dev_cupboard_all", dff="dev_cupboard_3", alpha=false, directory="models/dev/"},
        {id=2092, col="dev_cupboard_4", txd="dev_cupboard_all", dff="dev_cupboard_4", alpha=false, directory="models/dev/"},
        {id=2562, col="dev_kitchen_1", txd="dev_kitchen_all", dff="dev_kitchen_1", alpha=false, directory="models/dev/"},
        {id=2568, col="dev_kitchen_2", txd="dev_kitchen_all", dff="dev_kitchen_2", alpha=false, directory="models/dev/"},
        {id=2569, col="dev_kitchen_3", txd="dev_kitchen_all", dff="dev_kitchen_3", alpha=false, directory="models/dev/"},
        {id=2570, col="dev_kitchen_4", txd="dev_kitchen_all", dff="dev_kitchen_4", alpha=false, directory="models/dev/"},
        {id=2573, col="dev_kitchen_5", txd="dev_kitchen_all", dff="dev_kitchen_5", alpha=false, directory="models/dev/"},
        {id=2014, col="dev_tool_1", txd="dev_tool_all", dff="dev_tool_1", alpha=false, directory="models/dev/"},
        {id=2015, col="dev_tool_2", txd="dev_tool_all", dff="dev_tool_2", alpha=false, directory="models/dev/"},
        {id=2016, col="dev_tool_3", txd="dev_tool_all", dff="dev_tool_3", alpha=false, directory="models/dev/"},
        {id=2018, col="dev_tool_4", txd="dev_tool_all", dff="dev_tool_4", alpha=false, directory="models/dev/"},
        {id=2019, col="dev_tool_5", txd="dev_tool_all", dff="dev_tool_5", alpha=false, directory="models/dev/"},
        {id=2020, col="dev_tool_6", txd="dev_tool_all", dff="dev_tool_6", alpha=false, directory="models/dev/"},
        {id=2021, col="dev_tool_7", txd="dev_tool_all", dff="dev_tool_7", alpha=false, directory="models/dev/"},
        {id=2022, col="dev_tool_8", txd="dev_tool_all", dff="dev_tool_8", alpha=false, directory="models/dev/"},
        {id=1630, col="dev_tool_9", txd="dev_tool_all", dff="dev_tool_9", alpha=false, directory="models/dev/"},
        {id=3067, col="dev_tool_10", txd="dev_tool_all", dff="dev_tool_10", alpha=false, directory="models/dev/"},
        {id=1958, col="dev_tool_11", txd="dev_tool_all", dff="dev_tool_11", alpha=false, directory="models/dev/"},
        {id=3964, col="dev_tool_12", txd="dev_tool_all", dff="dev_tool_12", alpha=false, directory="models/dev/"},
        {id=3963, col="dev_tool_13", txd="dev_tool_all", dff="dev_tool_13", alpha=false, directory="models/dev/"},
        {id=3051, col="dev_other_1", txd="dev_other_all", dff="dev_other_1", alpha=false, directory="models/dev/"},
        {id=13360, col="dev_other_2", txd="dev_other_all", dff="dev_other_2", alpha=false, directory="models/dev/"},
        {id=9590, col="dev_other_3", txd="dev_other_all", dff="dev_other_3", alpha=false, directory="models/dev/"},
        {id=2025, col="dev_other_4", txd="dev_other_all", dff="dev_other_4", alpha=false, directory="models/dev/"},
        {id=3193, col="dev_other_5", txd="dev_other_all", dff="dev_other_5", alpha=false, directory="models/dev/"},
        {id=16353, col="dev_other_6", txd="dev_other_all", dff="dev_other_6", alpha=false, directory="models/dev/"},
        {id=14772, col="dev_other_7", txd="dev_other_all", dff="dev_other_7", alpha=false, directory="models/dev/"},
        {id=1429, col="dev_other_8", txd="dev_other_all", dff="dev_other_8", alpha=false, directory="models/dev/"},
    },
}